{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "application.serviceAccountName" . }}
  labels:
{{ include "application.labels" . | indent 4 }}
{{- end -}}
