{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "database.serviceAccountName" . }}
  labels:
{{ include "database.labels" . | indent 4 }}
{{- end -}}
