{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "service.serviceAccountName" . }}
  labels:
{{ include "service.labels" . | indent 4 }}
{{- end -}}
